yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='groups')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()
POST_TRUNCATE_NUMBER = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:POST_TRUNCATE_NUMBER]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        'Комментарии к посту', help_text='Оставьте комментарий'
    )
    created = models.DateTimeField(
        'Дата публикации комментария', auto_now_add=True
    )

    def __str__(self):
        return self.text[:POST_TRUNCATE_NUMBER]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст', 'group': 'Группа'}
        help_texts = {
            'text': 'Добавьте новую запись',
            'group': 'Выберете группу',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': 'Оставьте комментарий'}

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from .consts import POSTS_NUMBERS


@cache_page(20, key_prefix='index_page')
@vary_on_cookie
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_NUMBERS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).all()
    paginator = Paginator(post_list, POSTS_NUMBERS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    post_list = Post.objects.filter(author=author)
    paginator = Paginator(post_list, POSTS_NUMBERS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {'page_obj': page_obj, 'author': author, 'following': following}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm()
    post = Post.objects.get(id=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'is_edit': True,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(
            request, 'posts/create.html', {'form': form, 'is_edit': False}
        )
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user.username)


@login_required()
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).select_related('author', 'group')
    paginator = Paginator(post_list, POSTS_NUMBERS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_following_already = Follow.objects.filter(
        user=user, author=author
    ).exists()
    if user != author and not is_following_already:
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=user, author=author).delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
                Править
              {% else %}
                 Опубликовать
              {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post" enctype="multipart/form-data"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                 Добавить
              {% endif %}
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}
  

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Посты избранных авторов{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True%}
  <div class="container py-5">
  {% for post in page_obj %}
    {% include "includes/posts_rendering.html" with show_group_link=True  %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
{{title}}
{% endblock %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include "includes/posts_rendering.html" %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with index=True%}
  <div class="container py-5">
  {% for post in page_obj %}
    {% include "includes/posts_rendering.html" with show_group_link=True %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{post|truncatechars:9 }}
{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{post.pub_date|date:"d E Y"}}
            </li>
            <li class="list-group-item">
              {% if post.group %}
              Группа: {{post.group}}
              <br>
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{post.author}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{post.author.posts.count}}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{post.text}}
          </p>
          {% if post.author == user %}
          <a class="btn btn-primary" href="{% url 'posts:edit' post.id %}">
              редактировать запись
          </a>
          {% endif %}
          {% include "posts/includes/comments.html" %}
        </article>
      </div> 
    </main>
  </body>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  {{author}}
{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
          <div class="mb-5">
            <h1>Все посты пользователя {{author.username}} </h1>
            <h3>Всего постов: {{author.posts.count}} </h3>
            {% if following %}
              <a class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
              </a>
            {% elif author.username != user.username %}
              <a class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button">
                Подписаться
              </a>
            {% endif %}
          </div>
          {% for post in page_obj %}
           <article>
             {% include "includes/posts_rendering.html" with show_group_link=True %}
           </article>
           {% endfor %}
        {% include 'posts/includes/paginator.html' %}

      </div>
    </main>
  </body>
{% endblock %}